# This is the default Dockerfile template for building various 
# NuDocker images

FROM ubuntu:mm.nn

LABEL maintainer="Falk Herwig <fherwig@uvic.ca>"

COPY apt_packages_nudome.txt /tmp/apt_packages_nudome.txt

RUN apt-get update && \
    apt-get -y install $(cat /tmp/apt_packages_nudome.txt) && \
    apt-get autoremove --yes && apt-get clean all && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
	
RUN useradd -d /home/user -m -c "" user && \
    chown -R user:user /home/user && \
    chmod -R 775 /home/user/

USER user
COPY dot.bash_aliases /home/user/.bash_aliases

RUN (cd /tmp; wget https://zenodo.org/records/zzzzzzz/files/mesasdk-x86_64-linux-yyyymmdd.tar.gz) && \
    tar xvfz /tmp/mesasdk-x86_64-linux-yyyymmdd.tar.gz -C /home/user && \
    rm -f /tmp/mesasdk-x86_64-linux-yyyymmdd.tar.gz 

USER user
ENV HOME=/home/user
WORKDIR /home/user
